"""PDF report generation using reportlab with embedded matplotlib plots.

Matches the NeuroSynchrony PDF report style: uniform cyan spectra shading,
matching topomap colormap, and proper layout proportions.
"""

import io
import datetime
import numpy as np
from matplotlib.figure import Figure

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

import mne

from ..utils.constants import FREQ_BANDS, ZSCORE_VMIN, ZSCORE_VMAX


# Spectra colors (matching PDF)
_SPECTRUM_LINE_COLOR = "#3388CC"
_GRID_LINE_COLOR = "#CCDDEE"
_BAND_BOUNDARY_COLOR = "#AACCDD"
_HGRID_COLOR = "#DDDDDD"

# Band shading colors matching the app
_BAND_SHADING = {
    "Delta": {"range": (1.0, 4.0),  "color": "#D6EAF8"},
    "Theta": {"range": (4.0, 8.0),  "color": "#D5F5E3"},
    "Alpha": {"range": (8.0, 13.0), "color": "#FCF3CF"},
    "Beta":  {"range": (13.0, 25.0),"color": "#D4EFF7"},
}


class PDFReportGenerator:
    """Generates a PDF qEEG report with embedded plots."""

    def generate(self, analyzer, eeg_info, output_path, patient_info=None):
        """Create a multi-page PDF report."""
        doc = SimpleDocTemplate(
            output_path, pagesize=letter,
            topMargin=0.5 * inch, bottomMargin=0.5 * inch,
            leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "ReportTitle", parent=styles["Title"],
            fontSize=20, spaceAfter=6,
        )
        heading_style = ParagraphStyle(
            "ReportHeading", parent=styles["Heading2"],
            fontSize=14, spaceBefore=12, spaceAfter=6,
        )
        normal_style = styles["Normal"]

        elements = []

        # Header
        date_str = datetime.datetime.now().strftime("%B %d, %Y")
        elements.append(Paragraph("qEEG Analysis Report", title_style))
        elements.append(Paragraph(f"Generated: {date_str}", normal_style))
        if patient_info:
            info_lines = []
            if patient_info.get("file_name"):
                info_lines.append(f"File: {patient_info['file_name']}")
            if patient_info.get("meas_date"):
                info_lines.append(f"Recording Date: {patient_info['meas_date']}")
            info_lines.append(
                f"Channels: {patient_info.get('n_eeg_channels', '?')} EEG | "
                f"Sample Rate: {patient_info.get('sfreq', '?')} Hz | "
                f"Duration: {patient_info.get('duration_sec', 0):.0f}s"
            )
            for line in info_lines:
                elements.append(Paragraph(line, normal_style))
        elements.append(Spacer(1, 12))

        # Page 1: Magnitude Spectra
        elements.append(Paragraph("QEEG Magnitude Spectra", heading_style))
        spectra_img = self._render_spectra(analyzer)
        elements.append(Image(spectra_img, width=6.5 * inch, height=4 * inch))
        elements.append(Spacer(1, 12))

        # Topographic Maps
        elements.append(Paragraph("QEEG Relative Power", heading_style))
        elements.append(Paragraph(
            f"Z-Score Method: {analyzer.normative.get_method_label()}",
            normal_style
        ))
        topo_img = self._render_topomaps(analyzer, eeg_info)
        elements.append(Image(topo_img, width=6.5 * inch, height=3 * inch))

        elements.append(PageBreak())

        # Page 2: Band Power Table
        elements.append(Paragraph("Band Power Summary", heading_style))
        elements.append(self._make_power_table(analyzer))
        elements.append(Spacer(1, 12))

        # Asymmetry Table
        elements.append(Paragraph("Hemispheric Asymmetry", heading_style))
        elements.append(self._make_asymmetry_table(analyzer))
        elements.append(Spacer(1, 12))

        # Peak Frequencies Table
        elements.append(Paragraph("Peak Frequencies", heading_style))
        elements.append(self._make_peak_table(analyzer))

        # Footer
        elements.append(Spacer(1, 24))
        elements.append(Paragraph(
            "Generated by EEG Viewer v1.0",
            ParagraphStyle("Footer", parent=normal_style, fontSize=8, textColor=colors.grey),
        ))

        doc.build(elements)

    def _render_spectra(self, analyzer):
        """Render magnitude spectra matching the NeuroSynchrony PDF style."""
        fig = Figure(figsize=(10, 6), dpi=150)
        fig.set_facecolor("white")

        regions = ["Frontal", "Central", "Posterior"]
        for idx, region in enumerate(regions):
            ax = fig.add_subplot(3, 1, idx + 1)
            freqs, amplitude = analyzer.get_region_spectra(region)
            mask = (freqs >= 1) & (freqs <= 25)
            freqs_d = freqs[mask]
            amp_d = amplitude[mask]

            # Colored band shading (matching app)
            for band_name, band_info in _BAND_SHADING.items():
                f_low, f_high = band_info["range"]
                ax.axvspan(f_low, f_high, color=band_info["color"],
                           alpha=0.85, zorder=0)

            # Light 1 Hz gridlines
            for hz in range(1, 26):
                ax.axvline(hz, color=_GRID_LINE_COLOR, linewidth=0.3,
                           linestyle="-", zorder=1, alpha=0.6)

            # Band boundary dashes
            for boundary_hz in [4, 8, 13]:
                ax.axvline(boundary_hz, color=_BAND_BOUNDARY_COLOR,
                           linewidth=0.8, linestyle="--", zorder=2)
            ax.yaxis.grid(True, color=_HGRID_COLOR, linewidth=0.5, alpha=0.7)

            # Spectrum line
            ax.plot(freqs_d, amp_d, color=_SPECTRUM_LINE_COLOR, linewidth=1.2, zorder=5)

            # Auto-scale Y-axis with headroom
            max_amp = np.max(amp_d) if len(amp_d) > 0 else 1
            if max_amp <= 2.0:
                y_scale = np.ceil(max_amp * 2) / 2
            elif max_amp <= 5.0:
                y_scale = np.ceil(max_amp)
            else:
                y_scale = np.ceil(max_amp / 2) * 2
            if y_scale < max_amp * 1.1:
                y_scale = max_amp * 1.15
            ax.set_ylim(0, y_scale)
            ax.set_ylabel(f"{y_scale:.1f} µV", fontsize=8, fontweight="bold")
            ax.text(-0.1, 0.5, region, transform=ax.transAxes,
                    fontsize=10, fontweight="bold", va="center")
            ax.set_xlim(1, 25)
            ax.set_xticks([5, 10, 15, 20, 25])
            if idx == 2:
                ax.set_xlabel("Frequency (Hz)", fontsize=9)
            else:
                ax.set_xticklabels([])
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)

        fig.tight_layout(rect=[0.08, 0.02, 1.0, 0.98])
        buf = io.BytesIO()
        fig.savefig(buf, format="png", bbox_inches="tight", dpi=150)
        buf.seek(0)
        return buf

    def _render_topomaps(self, analyzer, eeg_info):
        """Render topographic maps matching the NeuroSynchrony PDF colormap."""
        from ..ui.topomap_widget import ZSCORE_CMAP

        fig = Figure(figsize=(14, 4.5), dpi=150)
        fig.set_facecolor("white")

        band_names = list(FREQ_BANDS.keys())
        for i, band_name in enumerate(band_names):
            ax = fig.add_axes([0.03 + i * 0.225, 0.08, 0.20, 0.78])
            zscores = analyzer.zscores[band_name]
            f_low, f_high = FREQ_BANDS[band_name]

            im, _ = mne.viz.plot_topomap(
                zscores, eeg_info, axes=ax,
                cmap=ZSCORE_CMAP, vlim=(ZSCORE_VMIN, ZSCORE_VMAX),
                show=False, contours=0, sensors=False,
            )
            ax.set_title(f"{band_name} ({f_low:.0f}-{f_high:.0f} Hz)",
                         fontsize=9, fontweight="bold")

        cbar_ax = fig.add_axes([0.93, 0.08, 0.02, 0.78])
        cbar = fig.colorbar(im, cax=cbar_ax)
        cbar.set_ticks([ZSCORE_VMIN, 0, ZSCORE_VMAX])
        cbar.set_ticklabels([f"{ZSCORE_VMIN:.1f} Z", "0", f"{ZSCORE_VMAX:.1f} Z"])

        buf = io.BytesIO()
        fig.savefig(buf, format="png", bbox_inches="tight", dpi=150)
        buf.seek(0)
        return buf

    def _make_power_table(self, analyzer):
        """Create a reportlab Table for band powers."""
        bands = list(FREQ_BANDS.keys())
        header = ["Channel"] + [f"{b} Abs" for b in bands] + [f"{b} Rel" for b in bands]
        data = [header]

        for i, ch in enumerate(analyzer.eeg_channels):
            row = [ch]
            for b in bands:
                row.append(f"{analyzer.band_powers[b][i]:.4e}")
            for b in bands:
                row.append(f"{analyzer.relative_powers[b][i]:.3f}")
            data.append(row)

        table = Table(data, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4a90d9")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 6),
            ("FONTSIZE", (0, 0), (-1, 0), 7),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f4ff")]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        return table

    def _make_asymmetry_table(self, analyzer):
        """Create a reportlab Table for hemispheric asymmetry."""
        bands = list(FREQ_BANDS.keys())
        header = ["Pair"] + bands
        data = [header]

        first_band = bands[0]
        for pair_idx, ((left, right), _) in enumerate(analyzer.asymmetry.get(first_band, [])):
            row = [f"{left}-{right}"]
            for b in bands:
                asym_list = analyzer.asymmetry.get(b, [])
                if pair_idx < len(asym_list):
                    row.append(f"{asym_list[pair_idx][1]:.4f}")
                else:
                    row.append("N/A")
            data.append(row)

        table = Table(data, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4a90d9")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f4ff")]),
        ]))
        return table

    def _make_peak_table(self, analyzer):
        """Create a reportlab Table for peak frequencies."""
        header = ["Channel", "Alpha Peak (Hz)", "Dominant Freq (Hz)"]
        data = [header]

        for ch in analyzer.eeg_channels:
            pf = analyzer.peak_freqs.get(ch, {})
            data.append([
                ch,
                f"{pf.get('alpha_peak', 0):.2f}",
                f"{pf.get('dominant', 0):.2f}",
            ])

        table = Table(data, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4a90d9")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f4ff")]),
        ]))
        return table
